[workspace]
members = [
	"enum-variant-utils",
	"enum-variant-utils-macros",
	"enum-variant-utils-tests",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
license = "MIT"
repository = "https://github.com/richardstephens/enum-variant-utils"
readme = "README.md"
edition = "2024"

[workspace.dependencies]
evutils = { path = "enum-variant-utils", version = "0.1.0"}
evutils-macros = { path = "enum-variant-utils-macros", version = "0.1.0"}
