[workspace]
members = [
	"enum-variant-utils",
	"enum-variant-utils-macros",
	"enum-variant-utils-tests",
]
resolver = "2"

[workspace.package]
description = "Handy helper utilities for working with enum variants"
version = "0.1.1"
license = "MIT"
repository = "https://github.com/richardstephens/enum-variant-utils"
readme = "README.md"
edition = "2024"
authors = ["Richard Stephens <richard@richst.dev>"]

[workspace.dependencies]
evutils = { path = "enum-variant-utils", version = "0.1.1" }
evutils-macros = { path = "enum-variant-utils-macros", version = "0.1.1" }
serde_json = "1"
